import type { MachineProfile } from "./types";

const INR = 8.5;
const CO2 = 0.82;

/**
 * Five SME machines. Profiles are nameplate + typical operating bands.
 * They are NOT the model. The model is learned from each machine's samples.
 */
export const PROFILES: MachineProfile[] = [
  {
    id: "IM-01",
    name: "Injection moulder",
    make: "Engel victory 150",
    hall: "Hall A · Bay 2",
    kind: "moulder",
    sensors: ["kw", "pf", "tempC", "vibRms", "currentA", "rejectPct"],
    ratedKw: 45,
    idleKw: 3.4,
    producingKw: 28.6,
    producingKwStd: 1.7,
    highLoadKw: 32.0,
    overloadKw: 42,
    pf: 0.91,
    tempC: 64,
    vibRms: 1.35,
    currentA: 51,
    rejectPct: 1.8,
    cycleSec: 22,
    unitsPerCycle: 2,
    bestSec: 0.078,
    historyDays: 18,
    learningTarget: "ml_ready",
    rupeePerKwh: INR,
    kgCo2PerKwh: CO2,
  },
  {
    id: "CNC-02",
    name: "CNC mill",
    make: "Haas VF-2",
    hall: "Hall A · Bay 5",
    kind: "cnc",
    sensors: ["kw", "pf", "tempC", "vibRms", "currentA"],
    ratedKw: 22,
    idleKw: 1.8,
    producingKw: 11.4,
    producingKwStd: 1.1,
    highLoadKw: 12.8,
    overloadKw: 20,
    pf: 0.86,
    tempC: 48,
    vibRms: 0.95,
    currentA: 22,
    rejectPct: 0.6,
    cycleSec: 95,
    unitsPerCycle: 1,
    bestSec: 0.31,
    historyDays: 9,
    learningTarget: "statistical",
    rupeePerKwh: INR,
    kgCo2PerKwh: CO2,
  },
  {
    id: "COMP-03",
    name: "Air compressor",
    make: "Atlas Copco GA 37",
    hall: "Utility · Compressor room",
    kind: "compressor",
    sensors: ["kw", "pf", "tempC", "currentA"],
    ratedKw: 37,
    idleKw: 8.5,
    producingKw: 29.2,
    producingKwStd: 2.4,
    highLoadKw: 32.7,
    overloadKw: 38,
    pf: 0.88,
    tempC: 78,
    vibRms: 2.1,
    currentA: 58,
    rejectPct: 0,
    cycleSec: 40,
    unitsPerCycle: 1,
    bestSec: 0.12,
    historyDays: 5,
    learningTarget: "statistical",
    rupeePerKwh: INR,
    kgCo2PerKwh: CO2,
  },
  {
    id: "EXTR-04",
    name: "Extruder",
    make: "Davis-Standard 90mm",
    hall: "Hall B · Line 1",
    kind: "extruder",
    sensors: ["kw", "pf", "tempC", "vibRms", "currentA", "rejectPct"],
    ratedKw: 75,
    idleKw: 6.2,
    producingKw: 48.5,
    producingKwStd: 2.2,
    highLoadKw: 54.3,
    overloadKw: 70,
    pf: 0.9,
    tempC: 188,
    vibRms: 1.8,
    currentA: 92,
    rejectPct: 2.4,
    cycleSec: 12,
    unitsPerCycle: 1,
    bestSec: 0.42,
    historyDays: 16,
    learningTarget: "ml_ready",
    rupeePerKwh: INR,
    kgCo2PerKwh: CO2,
  },
  {
    id: "PUMP-05",
    name: "Hydraulic pump",
    make: "Bosch Rexroth A10VSO",
    hall: "Hall B · Press 3",
    kind: "pump",
    sensors: ["kw", "pf", "tempC", "currentA"],
    ratedKw: 18,
    idleKw: 1.1,
    producingKw: 9.4,
    producingKwStd: 0.8,
    highLoadKw: 10.5,
    overloadKw: 16.5,
    pf: 0.84,
    tempC: 52,
    vibRms: 1.1,
    currentA: 18,
    rejectPct: 0,
    cycleSec: 8,
    unitsPerCycle: 1,
    bestSec: 0.055,
    historyDays: 1,
    learningTarget: "commissioning",
    rupeePerKwh: INR,
    kgCo2PerKwh: CO2,
  },
];
